#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application("Custom Command", "1.0");

$application->add(new CustomCommand());

$application->run();
